{% set name = "rich-click" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ewels/rich-click/archive/v{{ version }}.tar.gz
  sha256: d517b6abd9feb2d25824265990d320dc27e25b333463ebb05875ebf69193a49f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rich-click=rich_click.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - rich >=10
    - click >=7,<9

test:
  imports:
    - rich_click
  requires:
    - pip
  commands:
    - pip check
    - rich-click --help

about:
  home: https://github.com/ewels/rich-click
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Format click help output nicely with rich
  description: |
    Provides attractive help output from click,
    formatted with rich, with minimal customisation required.
  doc_url: https://github.com/ewels/rich-click
  dev_url: https://github.com/ewels/rich-click

extra:
  recipe-maintainers:
    - ewels
